# Generated by Django 4.2.6 on 2024-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontractorappointment',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='RECEIVED', max_length=100),
        ),
    ]
