# Generated by Django 4.2.6 on 2024-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookarcappointment',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='RECEIVED', max_length=100),
        ),
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plans',
            name='total_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
