# Generated by Django 4.2.6 on 2024-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitems',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='is_restocked',
            field=models.BooleanField(default=False),
        ),
    ]
